#!/bin/sh

LOCATION=~/.local/apps
NAME=i3

if [[ "$1" == "install" ]]; then
    rm -rf $LOCATION/$NAME
    cd $LOCATION
    git clone --depth=1 https://github.com/o4dev/i3
    cd $NAME
    sed '528,550d' src/ipc.c > src/ipc.c.tmp
    mv -f src/ipc.c.tmp src/ipc.c 
    make
elif [[ "$1" == "remove" ]]; then
    rm -rf $LOCATION/$NAME
elif [[ "$1" == "update" ]]; then
    cd $LOCATION/$NAME
    git pull
    make
elif [[ "$1" == "exists" ]]; then
    if [[ -e $LOCATION/$NAME/i3 ]]; then
        echo "yes"
    else
        echo "no"
    fi
fi
