#!/bin/bash

LOCATION=~/.local/apps
NAME=i3blocks

if [[ "$1" == "install" ]]; then
    rm -rf $LOCATION/$NAME
    cd $LOCATION
    git clone https://github.com/vivien/i3blocks
    cd $NAME
    git checkout a1782404c7d933145b048d0d1872ea40d7a293b6
    make
elif [[ "$1" == "remove" ]]; then
    rm -rf $LOCATION/$NAME
# elif [[ "$1" == "update" ]]; then
#     cd $LOCATION/$NAME
#     git pull
#     make
elif [[ "$1" == "exists" ]]; then
    if [[ -e $LOCATION/$NAME/i3blocks ]]; then
        echo "yes"
    else
        echo "no"
    fi
fi
